//
// Copyright (c) 2022.
// Created by Andy Pangaribuan. All Rights Reserved.
//
// This product is protected by copyright and distributed under
// licenses restricting copying, distribution and decompilation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: files/proto/ssync.proto

package sync_svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyLockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Action  string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *KeyLockRequest) Reset() {
	*x = KeyLockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_files_proto_ssync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLockRequest) ProtoMessage() {}

func (x *KeyLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_proto_ssync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLockRequest.ProtoReflect.Descriptor instead.
func (*KeyLockRequest) Descriptor() ([]byte, []int) {
	return file_files_proto_ssync_proto_rawDescGZIP(), []int{0}
}

func (x *KeyLockRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *KeyLockRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyLockRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *KeyLockRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KeyLockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Code    string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *KeyLockResponse) Reset() {
	*x = KeyLockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_files_proto_ssync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLockResponse) ProtoMessage() {}

func (x *KeyLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_proto_ssync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLockResponse.ProtoReflect.Descriptor instead.
func (*KeyLockResponse) Descriptor() ([]byte, []int) {
	return file_files_proto_ssync_proto_rawDescGZIP(), []int{1}
}

func (x *KeyLockResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *KeyLockResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyLockResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *KeyLockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_files_proto_ssync_proto protoreflect.FileDescriptor

var file_files_proto_ssync_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x73,
	0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x79, 0x6e, 0x63, 0x5f,
	0x73, 0x76, 0x63, 0x22, 0x6e, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x6b, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x51, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x76, 0x63, 0x2e,
	0x4b, 0x65, 0x79, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x16, 0x5a, 0x14, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_files_proto_ssync_proto_rawDescOnce sync.Once
	file_files_proto_ssync_proto_rawDescData = file_files_proto_ssync_proto_rawDesc
)

func file_files_proto_ssync_proto_rawDescGZIP() []byte {
	file_files_proto_ssync_proto_rawDescOnce.Do(func() {
		file_files_proto_ssync_proto_rawDescData = protoimpl.X.CompressGZIP(file_files_proto_ssync_proto_rawDescData)
	})
	return file_files_proto_ssync_proto_rawDescData
}

var file_files_proto_ssync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_files_proto_ssync_proto_goTypes = []interface{}{
	(*KeyLockRequest)(nil),  // 0: sync_svc.KeyLockRequest
	(*KeyLockResponse)(nil), // 1: sync_svc.KeyLockResponse
}
var file_files_proto_ssync_proto_depIdxs = []int32{
	0, // 0: sync_svc.SyncService.KeyLock:input_type -> sync_svc.KeyLockRequest
	1, // 1: sync_svc.SyncService.KeyLock:output_type -> sync_svc.KeyLockResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_files_proto_ssync_proto_init() }
func file_files_proto_ssync_proto_init() {
	if File_files_proto_ssync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_files_proto_ssync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyLockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_files_proto_ssync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyLockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_files_proto_ssync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_files_proto_ssync_proto_goTypes,
		DependencyIndexes: file_files_proto_ssync_proto_depIdxs,
		MessageInfos:      file_files_proto_ssync_proto_msgTypes,
	}.Build()
	File_files_proto_ssync_proto = out.File
	file_files_proto_ssync_proto_rawDesc = nil
	file_files_proto_ssync_proto_goTypes = nil
	file_files_proto_ssync_proto_depIdxs = nil
}
